name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    - name: Pack nugets
      run: dotnet pack -c Release --no-build --output ./nuget -p:PackageVersion=$RELEASE_VERSION
    - name: Prep packages
      run: dotnet nuget add source --username MarcUnterseh --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/MarcUnterseh/index.json"
    - name: Publish to GitHub packages 
      run: dotnet nuget push **\*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"